In [1]:
import numpy as np
import cv2 as cv2
from matplotlib import pyplot as plt

#### Read image and find edges

In [33]:
# Read image. Flags: 1=color, 0=grayscale, -1=unchanged.
img_color = cv2.imread('test1.jpg', 1)

# Resize image
scale = 0.5
height = int(img_color.shape[0] * scale)
width = int(img_color.shape[1] * scale)
dim = (width, height)
img_color = cv2.resize(img_color, dim, interpolation = cv2.INTER_AREA)

# Convert to gray scale
gray = cv2.cvtColor(img_color, cv2.COLOR_BGR2GRAY)

# Remove noise with gaussian blur
edges = cv2.GaussianBlur(gray,(7,7),0)
 
# Edges to binary (black and white)
ret,edges = cv2.threshold(edges,200,255,cv2.THRESH_BINARY)

# Remove isolated pixels
edges = cv2.GaussianBlur(edges,(5,5),0)
edges = cv2.threshold(edges, 150 , 250, cv2.THRESH_BINARY)
edges = edges[1]

edges_clone = edges.copy()

cv2.imshow("Edges", edges)
cv2.waitKey(0)

# cv2.imwrite('Edges.jpg', edges)

-1

In [34]:
# Black-White image means that pixel value is either 0 (Black) or 250 (White)
# Counts non-zero array elements.

retval = cv2.countNonZero(edges_clone)
retval

# Find the unique elements of an array --> find unique colors
np.unique(edges_clone)

1172

array([  0, 250], dtype=uint8)

In [6]:
# Function info() to get array description

def info(name, a):
    print(f"{name} has dim {a.ndim}, shape {a.shape}, size {a.size}, and dtype {a.dtype}:")

info("Edges array", edges_clone)

Edges array has dim 2, shape (1653, 2338), size 3864714, and dtype uint8:


In [7]:
# Return the indices of the elements that are non-zero and pixels are white

whitePX = np.asarray(edges_clone == 250).nonzero()
whitePX

(array([  56,   56,   56, ..., 1652, 1652, 1652], dtype=int64),
 array([ 361,  362,  363, ..., 1703, 1704, 1705], dtype=int64))

In [8]:
edges_clone[56,361] # --> should be 250 (white)
edges_clone[10,1] # --> should be 0 (black)


250

0

In [9]:
# Create and dray circle according to white points coordination
# x,y - circle center coordinates, 10 - radius, 1 - thickness

def drawCircle(img, x,y):
    cv2.circle(img,(x,y),10,(250,250,250),1)

In [10]:
# PRINT CIRCLES AROUND WHITE PIXELS

for j in range(len(whitePX[0])-1):
    drawCircle(edges_clone,whitePX[1][j], whitePX[0][j])

cv2.imshow('Edges', edges_clone) 
# cv2.imwrite('Circe.png', edges)
  
# Allows us to see image 
# untill closed forcefully 
cv2.waitKey(0) 
cv2.destroyAllWindows() 

-1

#### Compare two images and draw growing line

In [12]:
# Read image. Flags: 1=color, 0=grayscale, -1=unchanged.
img_color = cv2.imread('test2.jpg', 1)

# Resize image
scale = 0.5
height = int(img_color.shape[0] * scale)
width = int(img_color.shape[1] * scale)
dim = (width, height)
img_color = cv2.resize(img_color, dim, interpolation = cv2.INTER_AREA)

# Convert to gray scale
gray = cv2.cvtColor(img_color, cv2.COLOR_BGR2GRAY)

# Remove noise with gaussian blur
edges = cv2.GaussianBlur(gray,(7,7),0)
 
# Edges to binary (black and white)
ret,edges = cv2.threshold(edges,200,255,cv2.THRESH_BINARY)

# Remove isolated pixels
edges = cv2.GaussianBlur(edges,(5,5),0)
edges = cv2.threshold(edges, 150 , 250, cv2.THRESH_BINARY)
edges2 = edges[1]

edges2_clone = edges2.copy()

cv2.imshow("Edges", edges2)
cv2.waitKey(0)

# cv2.imwrite('Edges.jpg', edges)

-1

In [14]:
# Black-White image means that pixel value is either 0 (Black) or 250 (White)
# Counts non-zero array elements.

retval = cv2.countNonZero(edges2_clone)
retval

# Find the unique elements of an array --> find unique colors
np.unique(edges2_clone)

634

array([  0, 250], dtype=uint8)

In [15]:
# Function info() to get array description

def info(name, a):
    print(f"{name} has dim {a.ndim}, shape {a.shape}, size {a.size}, and dtype {a.dtype}:")

info("Edges array", edges2_clone)

Edges array has dim 2, shape (1653, 2338), size 3864714, and dtype uint8:


In [16]:
# Return the indices of the elements that are non-zero and pixels are white

whitePX = np.asarray(edges2_clone == 250).nonzero()
whitePX

(array([  57,   57,   57,   57,   58,   58,   58,   58,   58,   59,   59,
          59,   59,   59,   59,   60,   60,   60,   60,   60,   60,   60,
          60,   61,   61,   61,   61,   61,   61,   61,   61,   61,   62,
          62,   62,   62,   62,   62,   62,   62,   62,   62,   63,   63,
          63,   63,   63,   63,   63,   63,   63,   63,   63,   64,   64,
          64,   64,   64,   64,   64,   64,   64,   64,   64,   64,   65,
          65,   65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
          66,   66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
          66,   66,   67,   67,   67,   67,   67,   67,   67,   67,   67,
          67,   67,   67,   67,   68,   68,   68,   68,   68,   68,   68,
          68,   68,   68,   68,   68,   68,   69,   69,   69,   69,   69,
          69,   69,   69,   69,   69,   69,   69,   69,   70,   70,   70,
          70,   70,   70,   70,   70,   70,   70,   70,   70,   70,   71,
          71,   71,   71,   71,   71, 

In [17]:
# PRINT CIRCLES AROUND WHITE PIXELS

for j in range(len(whitePX[0])-1):
    drawCircle(edges2_clone,whitePX[1][j], whitePX[0][j])

cv2.imshow('Edges', edges2_clone) 
# cv2.imwrite('Circe.png', edges)
  
# Allows us to see image 
# untill closed forcefully 
cv2.waitKey(0) 
cv2.destroyAllWindows() 

-1

In [28]:
edges2.shape

(1653, 2338)

In [27]:
edges.shape

(1653, 2338)

In [29]:
result = np.subtract(edges2,edges)
print ('the difference =', result)

the difference = [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [30]:
info("Edges array", edges2)

Edges array has dim 2, shape (1653, 2338), size 3864714, and dtype uint8:


In [31]:
info("Edges array", edges)

Edges array has dim 2, shape (1653, 2338), size 3864714, and dtype uint8:


In [32]:
retval = cv2.countNonZero(result)
retval


660